# -*- coding: utf-8 -*-
"""first screening task

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OIwNsb8uXKUh9ohwUnGLJxBdHdBPyokQ
"""

!pip install python-pptx

# import required things
from pptx import Presentation 
from pptx.util import Inches, Pt
from pptx.enum.text import PP_PARAGRAPH_ALIGNMENT

import pptx
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

# Creating Object
ppt = pptx.Presentation()

# To create blank slide layout, use the index 6
blank_slide_layout = ppt.slide_layouts[6]

# Slide 1
slide1 = ppt.slides.add_slide(blank_slide_layout)

# For adjusting the Margins in inches
left = top = Inches(1)
width = height = Inches(8)

# Creating textBox
txBox = slide1.shapes.add_textbox(left, top, width, height)

# Read content from sample_slide1_input.txt file
with open("sample_slide1_input.txt", "r") as f:
    slide1_content = f.read()

# Creating textFrames
tf = txBox.text_frame

# Adding Paragraphs
p = tf.add_paragraph()

# Adding text
p.text = slide1_content
p.font.name = 'Love Ya Like A Sister Regular'
p.font.size = Pt(10)

# Set the text alignment to center
p.alignment = PP_ALIGN.CENTER

# Set the text wrapping mode to "tight"
tf.word_wrap = True

# Slide 2
slide2 = ppt.slides.add_slide(blank_slide_layout)

# Creating textBox for slide 2
txBox2 = slide2.shapes.add_textbox(left, top, width, height)

# Read content from sample_slide2_input.txt file
with open("sample_slide2_input.txt", "r") as f:
    slide2_content = f.read()

# Creating textFrames for slide 2
tf2 = txBox2.text_frame

# Adding Paragraphs for slide 2
p2 = tf2.add_paragraph()

# Adding text for slide 2
p2.text = slide2_content
p2.font.name = 'Love Ya Like A Sister Regular'
p2.font.size = Pt(10)

# Set the text alignment to center
p2.alignment = PP_ALIGN.CENTER

# Set the text wrapping mode to "tight" for slide 2
tf2.word_wrap = True

# Save the file
ppt.save('task_1.pptx')

print("done")

